name    'frib-archiver_appliance'
version '0.1.0'
source 'https://stash.nscl.msu.edu/scm/deploy/puppet_module_archiver_appliance.git'
author 'konrad'
license 'MIT License (Expat)'
summary 'Puppet module for EPICS Archiver Appliance'
description 'Module for installation and configuration of EPICS Archiver Appliance. Allows configuration of a multi-node cluster.'
project_page 'https://stash.nscl.msu.edu/projects/DEPLOY/repos/puppet_module_archiver_appliance'

dependency 'puppetlabs/mysql'
dependency 'puppetlabs/apache'
dependency 'puppetlabs/apt'
dependency 'smarchive/archive'
